name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v16
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix-build
          cd examples/postgres
          ../../result-2/bin/xpg-core build

      - name: Test
        run: |
          cd examples/postgres
          ../../result-2/bin/xpg-core psql -v ON_ERROR_STOP=1 -c "SELECT true;"
          ../../result-2/bin/xpg-core test

      - name: Upload to cachix
        run: nix-build | cachix push nxpg


  build-on-macos:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Use Cachix Cache
        uses: cachix/cachix-action@v16
        with:
          name: nxpg
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: nix-build | cachix push nxpg
